# Generated by Django 4.2.1 on 2023-06-02 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogpost", "0003_alter_esicommodel_compound_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ESI_descriptor_Model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("compound_name", models.CharField()),
                ("smiles", models.CharField()),
                ("lpv", models.FloatField(max_length=10)),
                ("c_s0", models.FloatField(max_length=10)),
                ("s0_c", models.FloatField(max_length=10)),
                ("eav", models.FloatField(max_length=10)),
                ("a_s0", models.FloatField(max_length=10)),
                ("s0_a", models.FloatField(max_length=10)),
                ("stv", models.FloatField(max_length=10)),
                ("t1_s0", models.FloatField(max_length=10)),
                ("s0_t1", models.FloatField(max_length=10)),
                ("esolv", models.FloatField(max_length=10)),
                ("dm", models.FloatField(max_length=10)),
                ("vmol", models.FloatField(max_length=10)),
                ("b1", models.FloatField(max_length=10)),
                ("b2", models.FloatField(max_length=10)),
                ("b3", models.FloatField(max_length=10)),
            ],
        ),
    ]
