# Generated by Django 4.2.1 on 2023-06-02 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogpost", "0004_esi_descriptor_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="esi_descriptor_model",
            name="b1",
            field=models.FloatField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="esi_descriptor_model",
            name="b2",
            field=models.FloatField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="esi_descriptor_model",
            name="b3",
            field=models.FloatField(default=None, max_length=10, null=True),
        ),
    ]
