# Generated by Django 4.2.1 on 2023-06-13 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogpost", "0005_alter_esi_descriptor_model_b1_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="question_Model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.CharField()),
                ("question_title", models.CharField()),
                ("question", models.TextField()),
                (
                    "public_permission",
                    models.CharField(
                        choices=[
                            ("approval", "approval"),
                            ("disapproval", "disapproval"),
                        ],
                        max_length=50,
                    ),
                ),
                ("email_adress", models.CharField()),
                (
                    "question_situation",
                    models.CharField(
                        choices=[
                            ("answered", "answered"),
                            ("unanswered", "unanswered"),
                            ("on_hold", "on_hold"),
                        ],
                        max_length=50,
                    ),
                ),
                ("reply", models.TextField()),
            ],
        ),
    ]
