# Generated by Django 4.2.1 on 2023-06-16 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogpost", "0006_question_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogmodel",
            name="category",
            field=models.CharField(
                choices=[("business", "公開許可"), ("life", "公開不許可"), ("other", "その他")],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="question_model",
            name="date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
