# Generated by Django 4.2.1 on 2023-06-16 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogpost", "0007_alter_blogmodel_category_alter_question_model_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question_model",
            name="email_adress",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="question_model",
            name="question_situation",
            field=models.CharField(
                choices=[
                    ("answered", "answered"),
                    ("unanswered", "unanswered"),
                    ("on_hold", "on_hold"),
                ],
                default="unanswered",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="question_model",
            name="question_title",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="question_model",
            name="reply",
            field=models.TextField(blank=True, null=True),
        ),
    ]
