# Generated by Django 4.2.1 on 2023-06-16 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogpost", "0008_alter_question_model_email_adress_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question_model",
            name="email_adress",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
